os: linux
dist: trusty
cache: false
sudo: required
language: bash
services: docker
env:
  matrix:
  - ARCH=x86_64 PUID=1000 PGID=1000
  - ARCH=armhf PUID=1001 PGID=1001
  global:
  - secure: Mbs250F1xkCjM6/ZpQoHlZFiMV5N6XygmZTvPTillkUlqGh9oMBLIudbl5L+SgKxILYa50KoI2tdVddt9cmvSkKEDfDMOWS8POkfoxWCK/oM8XCWlkiKypRnFxE7nbNLaM/n+kh/IfvUYRrw5Clt367U3X9qh6/RtieVNO45VMN7jGn49+2dGyr07pV1D5JABBBfrG98ASeHakgxwJ4I++iFwGJd9PbIBKazSBVBSwo2U4zwTkpK9dmjqLjxOnS1VF4ZkOainSii7goWEpWlw3Uw71IpHNCdf5Am7R76bPxQNW1hOiFGQRnLKwgTUvvmsykEdUfAFo5ys0SHxSslAga9u/nNBeEcVAP/zAwmArRv9ZgJ5AGEEGb37ofqXP5n/3ur1++DeMgU6K1JWoPBb2zm0XLDPyyC7MCmMfW4LTe1tAWohTQOZhbMVOsHlsJsvvoFLmE62saq3Lz/g7vCZyTsZZXzow6JIvzC+N0bHjo8PbZrMSwd39FKlQ8fV+5bQZoBeRXWH3XeV7c0LbQS/KerkSSLHKp9k09VuJ5AypQi6qTVHMERor19TW7RABTCKGMNzlVgGhEQG29IFs2S7JpcoqKE64RdA+d7RZudJTuVrqJhTFommeIE0mf0qyOyC30jWl58UmoltkXv2k7ZBzOy14kIb1xfjQ2oTxPB6J0=
  - secure: azZNlvlCXn9ikr683vKj8sxJia2gBKRwWZ0QS3HDFym76tQvVVhxe/sSp26rNGnW64xEDCE3KVK1QjWx0kgH4MSvJhr/X08qggRH+NuQiDupcz8G/fhOIqS1VSFdOZAIa7nb8YS5KT9/c72pcxuXVOk23STMwgFqd/2FZ2Ix2f2ppW5H3Jd95KPhqfIdOH4UzEjpNYh0VHEsLGmZOTPR2nIAjb3vJcFZ1ZSjE6Jb9U9Kmkz6mcfiPMBx2hJmino9pTXm2nc3iOUgC0G9pWfZ87ioePem/SzPzZe8S/QB7zl13NUlzPdFI1VZc2maQbyXVRHQSL/rESxNbTMMFGY61dxLsQAaFgY1H/VYSyLI/kFwTgLSz9lcM1DVQo2NYQ3DJazNdSvvihvPxxv2I5mlWAHSiaIWYhHmeDzfIpOZK6jAdaN9OZl2rJJKxA2LyoIhZ5WjYV5hRlWGajK3/1tApukBWhbsLL8rgamiT1y8Htz4yCwmx1MiZE3WbqxQZhjNBHUzlvjB47R7HQYV5VT9ll356hPm7Z3FERMSVsYMlzxqRSRqC1u2A0Z8lhUdiMl8tpvTWJUDivPW8hGI/gr9+7uo0H0edJnn7m2ZbkqQtzhFvKk7gbCIkfzdZL0Jf4CSnaZwAtslocucS4zwovZahUwMOfrLtyQ2W6GcJgroC8Q=
install: true
before_script:
- docker --version
- make --version
script:
- make ARCH=${ARCH} PUID=${PUID} PGID=${PGID} build test
after_success:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- make ARCH=${ARCH} push
after_script:
- docker logout
- make clean
